name: Build and Publish EnScan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17'

    - name: Install dependencies
      run: go mod download

    - name: Build EnScan
      run: go build -o EnScan

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: EnScan
        path: ./EnScan
